clients/urls.py
"""
package: clients
description: urls
"""
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('registration', views.PhoneVerificationView.as_view(), name='registration-contacts'),
    path('registration/<slug:slug>', views.RegisterView.as_view(), name='registration'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tm_site.urls', namespace='tm_site')),
    path('admin/', admin.site.urls),
    path('auth/', include('clients.urls', namespace='clients')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Texnomart Test</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">

      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Texnomart Home</h1>
{% if user.is_authenticated %}
Вы авторизованы
{% else %}
Вы не авторизованы
{% endif %}
{{user}}

  <p>Welcome to <em>Texnomart Test Page</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

<a href="{% url 'clients:registration-contacts' %}">Регистрация</a>
<a href="{% url 'clients:login' %}">Войти</a>
<a href="{% url 'clients:logout' %}">Выйти</a>

{% endblock %}